// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Set them in your deployment environment.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    let claimsData: { claims: Record<string, unknown> } | null = null;
    let claimsError: Error | null = null;
    try {
      const result = await supabase.auth.getClaims(token);
      claimsData = result.data;
      claimsError = result.error as Error | null;
    } catch (e) {
      console.error('[requireSupabaseAuth] getClaims threw:', e instanceof Error ? e.message : String(e));
      throw new Error('Unauthorized: Token verification failed');
    }

    if (claimsError || !claimsData?.claims) {
      console.error('[requireSupabaseAuth] getClaims error:', claimsError?.message ?? 'no claims');
      throw new Error('Unauthorized: Invalid token');
    }

    const sub = claimsData.claims['sub'];
    if (!sub || typeof sub !== 'string') {
      throw new Error('Unauthorized: No user ID found in token');
    }

    console.log('[requireSupabaseAuth] auth OK, userId:', sub);
    return next({
      context: {
        supabase,
        userId: sub,
        claims: claimsData.claims,
      },
    });
  },
);
